# Use an official Python runtime as a parent image
FROM python:3.11

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the local directory contents into the container
COPY . .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir confluent_kafka protobuf
# Copy the entire src directory contents into the container


# Run the script when the container launches
CMD ["python", "./SmartBus_Producer.py"]

