# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: smartbus.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0esmartbus.proto\x12\x08smartbus\"$\n\x08Location\x12\x0b\n\x03lat\x18\x01 \x01(\x01\x12\x0b\n\x03lon\x18\x02 \x01(\x01\"w\n\x08\x42lackBox\x12\x14\n\x0c\x61\x63\x63\x65leration\x18\x01 \x01(\x02\x12\x0f\n\x07\x62raking\x18\x02 \x01(\x02\x12\x18\n\x10\x66uel_consumption\x18\x03 \x01(\x02\x12\x15\n\rtire_pressure\x18\x04 \x01(\x02\x12\x13\n\x0b\x65rror_codes\x18\x05 \x03(\x05\"\xc0\x02\n\x07\x42usData\x12\x0e\n\x06\x62us_id\x18\x01 \x01(\t\x12\x10\n\x08\x62us_type\x18\x02 \x01(\t\x12$\n\x08location\x18\x03 \x01(\x0b\x32\x12.smartbus.Location\x12\x14\n\x0c\x62us_capacity\x18\x04 \x01(\x05\x12\x15\n\rpeople_in_bus\x18\x05 \x01(\x05\x12\x14\n\x0c\x64riving_time\x18\x06 \x01(\x02\x12\x15\n\rdriving_speed\x18\x07 \x01(\x02\x12\x1a\n\x12\x65ngine_temperature\x18\x08 \x01(\x02\x12\x11\n\ttimestamp\x18\t \x01(\x01\x12%\n\tblack_box\x18\n \x01(\x0b\x32\x12.smartbus.BlackBox\x12\x14\n\nfuel_level\x18\x0b \x01(\x02H\x00\x12\x17\n\rbattery_level\x18\x0c \x01(\x02H\x00\x42\x0e\n\x0cpower_sourceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'smartbus_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LOCATION']._serialized_start=28
  _globals['_LOCATION']._serialized_end=64
  _globals['_BLACKBOX']._serialized_start=66
  _globals['_BLACKBOX']._serialized_end=185
  _globals['_BUSDATA']._serialized_start=188
  _globals['_BUSDATA']._serialized_end=508
# @@protoc_insertion_point(module_scope)
