# Use an official Python runtime as a parent image
FROM python:3.11

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the consumer script into the container
COPY SmartStation_Producer.py .

# Install any needed packages specified in requirements.txt
# Assuming zmq and asyncio are needed, for example
RUN pip install --no-cache-dir pyzmq asyncio

# Run SmartStation_Consumer.py when the container launches
CMD ["python", "-u", "./SmartStation_Producer.py"]
