# Use an official Python runtime as a parent image
FROM python:3.11

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the subscriber script into the container
COPY SmartBus_Processor.py .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir pyzmq

# Run SmartBus_Processor.py when the container launches
CMD ["python", "-u", "./SmartBus_Processor.py"]
